name: painelexternal2
description: "A new Flutter project."

# O seguinte impede que o pacote seja publicado acidentalmente no pub.dev.
publish_to: 'none' # Remova esta linha se desejar publicar no pub.dev

# Definindo a versão e número de build para o seu aplicativo.
# Exemplo de versão: 1.2.43+1
version: 1.0.0+1

# Definindo o SDK para a versão compatível.
environment:
  sdk: ">=3.5.3 <4.0.0"

# Dependências para o projeto
dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  cupertino_icons: ^1.0.8
  flutter_animate: ^4.0.3
  http: ^1.2.2
  flutter_secure_storage: ^8.0.0
  uuid: ^3.0.0
  device_info_plus: ^10.0.1
  web_socket_channel: ^2.2.0
  shared_preferences: ^2.0.9
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0 # Use o símbolo ^ para indicar a versão mínima
  webview_flutter: ^4.0.6
  google_mobile_ads: ^5.1.0 # Verifique se há versões mais recentes
  url_launcher: ^6.0.0
  timezone: ^0.9.4
  video_player: ^2.4.5  # ou a versão mais recente disponível

# Dependências de desenvolvimento
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.2 # Gerar ícones para Android e iOS
  flutter_lints: ^4.0.0

# Configuração para gerar ícones de aplicativos para Android e iOS
flutter_icons:
  android: true
  ios: true
  adaptive_icon_background: "#ffffff" # Cor de fundo ou caminho para uma imagem de fundo
  adaptive_icon_foreground: "assets/icon/app_icon.png" # O caminho da imagem do ícone
  image_path: "assets/icon/app_icon.png" # O caminho da imagem do ícone para iOS
  
# Define se o projeto usará o Material Design e os assets
flutter:
  uses-material-design: true
  assets:
    - assets/icon/ # Certifique-se de que esta pasta contém o ícone
